### ISSUE TITLE
Not all samples are pushed in influxdb

### ISSUE THREAD

**Issue by AjaySinghMono** [NovaTecConsulting/JMeter-InfluxDB-Writer#10]
I am using 1.1 version of JMeter-InfluxDB-Writer with Jmeter 3.1.
And I facing issue as not all sample are pushed in influx db. For e.g. my JTL count shows total 40k hits & influxdb count shows 32k hits.

**Comment by gokhansengun** [comment]
This has already been resolved in master but a new version has to be generated. If you can build the master yourself that will do it, otherwise maintainer has to create a new version on 1.1

**Comment by AlexanderWert** [comment]
Resolved in release 1.2.
