### ISSUE TITLE
Sub Sample Request are not being written to the backend

### ISSUE THREAD

**Issue by MooreDerek** [NovaTecConsulting/JMeter-InfluxDB-Writer#11]
I have a fix for the 'JMeterInfluxDBBackendListenerClient.java' that captures all Sub SampleResult. I can post the code or if you can add me as a contributor I'm happy to create a Pull Request. @AlexanderWert, @gokhansengun

**Comment by gokhansengun** [comment]
In GitHub, everybody is a contributor. Just fork the repository do your change in your branch and send a PR. Please make sure you clearly note which problem you solve. In my opinion, sub sample's timing should be optional to capture if wanted to be captured. Some of the use cases do not require it to be captured.

**Comment by Amaradana** [comment]
I think logging sub samplers its all depends on your Transaction controller, if you have transaction controller and if you check generate parent sampler, it generates only transaction controllers but not sub samplers, if its unchecked you should be able to write everything to influxdb, so even if this change is being implementing I think there should be an option to turn it on or off, as most cases this might not be useful IMHO.

**Comment by AlexanderWert** [comment]
resolved in #12
