### ISSUE TITLE
Help on building the table in grafana

### ISSUE THREAD

**Issue by Amaradana** [NovaTecConsulting/JMeter-InfluxDB-Writer#13]
Hi,

First thank you so much for adding test Name in the requestsRaw table.

I was trying to build a query based on 2 tests, i know this is not an issue, but am currently stuck completely. I request you to please help me in building query or providing your thoughts on it. I did not know how to approach you guys 

I have 2 sets of data, basically i want to compare response time of 2 tests

time,errorCount,nodeName,requestName,responseTime,testName,threadName
2017-06-13T11:07:00.637817217Z.0."Test-Node"."Transaction1".425."SmokeTest1"."ThroudGroup 1-1"
2017-06-13T11:07:00.637817217Z.0."Test-Node"."Transaction1".425."SmokeTest2"."ThroudGroup 1-1"

how do i build the
![image](https://user-images.githubusercontent.com/27474379/27118147-94b75460-50f7-11e7-8cda-6fec2e82fdfd.png)

Request you to please help on this

**Comment by Amaradana** [comment]
I almost got this done with new version of influx db and grafana. hence this issue can be closed

**Comment by musanas** [comment]
@Amaradana Can you please throw some lights here, how you have done it ?

Thanks

**Comment by Amaradana** [comment]
You need to have mutliple query added make sure both queries of avg name is different and sort by transaction name

**Comment by musanas** [comment]
@Amaradana Were you able to filter the result based on test type ( say as given in your example "SmokeTests") .. like viewing SmokeTest1 only then SmokeTest2 only like that ? I could query influxdb only based on Time, not based on any other tag vaue like test name or test node .. .any idea on that ?
