### ISSUE TITLE
Backend Listener: Can't keep influxDBUser blank

### ISSUE THREAD

**Issue by shanep2300** [NovaTecConsulting/JMeter-InfluxDB-Writer#17]
Our database doesn't use a user or password. When I click save, it defaults the user back to jmeter.

Edit: Doesn't seem to cause issue with test just thought I'd bring it up.

**Comment by shanep2300** [comment]
Never mind. I just edited to code to remove the default string.

**Comment by 2012ucp1544** [comment]
There is a mandate to use username, password for influxdb.
Why this restriction is there?
Shouldn't this be flexible enough to support both usecases, as InfluxDb supports without username/password.
Please look into this.
