### ISSUE TITLE
Unexpected status line Error while running JMeter with BackendListener

### ISSUE THREAD

**Issue by gopi-nath** [NovaTecConsulting/JMeter-InfluxDB-Writer#24]
Hi,
I'm getting the following error while running the jmeter test plan with the backend listener. 
![screenshot from 2018-07-25 14-37-32](https://user-images.githubusercontent.com/21693479/43191192-4d319f2c-9018-11e8-82aa-fdf012b3f2ea.png)

Following is the BackendListener conf in JMeter:
![screenshot from 2018-07-25 14-29-08](https://user-images.githubusercontent.com/21693479/43191114-22e168e2-9018-11e8-809e-c017ebedd8b6.png)

Steps were followed from https://grafana.com/dashboards/1152
This error is occuring only in my staging environment. In my local, it is all working fine.
Also without the BackendListener part, the test plan is working fine.  
I've made sure connection between the servers where jmeter and influxdb is running are whitelisted. (For port 8086)

**Comment by gopi-nath** [comment]
@AlexanderWert Any help on this ?

**Comment by gopi-nath** [comment]
this is fixed.

**Comment by jkdihenkar** [comment]
It was an SSL Error and HTTPS scheme was not implemented. 

Fix is added here - https://github.com/NovatecConsulting/JMeter-InfluxDB-Writer/pull/27
