### ISSUE TITLE
Enhancement : Please also add testName in the requestsRaw table 

### ISSUE THREAD

**Issue by Amaradana** [NovaTecConsulting/JMeter-InfluxDB-Writer#4]
Hi,

This plugin just works great, so simple to understand the tables and easy to pull the response times etc. How ever if we want to build a comparison report when integrated with JMeter, Its not possible, as the table  testStartEnd logs 2 entries for the test, and this would be when test got started and test got finished , so it would be nice to add the TestName also in the  requestsraw table and this could make easier to build any custom queries

**Comment by gokhansengun** [comment]
@Amaradana I also need this and I have included it in my PR #5

**Comment by AlexanderWert** [comment]
Resolved with #5
